### ISSUE TITLE
.map() .toVector with length constraints 

### ISSUE THREAD

**Issue by mio-19** [Iltotore/iron#273]
**Is your feature request related to a problem? Please describe.**
iron can't detect that methods like `.map` and `.toVector` keep length unchanged. 

**Describe the solution you'd like**
Add logic for them on compile-time

**Describe alternatives you've considered**

**Comment by Iltotore** [comment]
The problem is unfortunately out of the scope of Iron in its current state. In order to achieve this, the best way would be to redefine `map`, `toVector` etc. signatures, maybe in a separated class (look at Cats'`NonEmptyList` for example).

It might be possible to create a compiler-plugin for that or just support in during compile-time refinement but there are far too many methods in the same situation to handle them all so I'm in favor of not adding specific support for `map` and `toVector` and use `assume` when necessary instead.
