### ISSUE TITLE
Automatic conversion from uncostrained type no longer works in Scala 3.1.1

### ISSUE THREAD

**Issue by mcallisto** [Iltotore/iron#51]
**Describe the bug**
Scala environment: JVM
Scala version: 3.1.1
Iron version: 1.2.0

**Reproduction steps**
```
import io.github.iltotore.iron.*
import io.github.iltotore.iron.constraint.*
import io.github.iltotore.iron.numeric.constraint.*

def mult(x: Int > 0, y: Int > 0): Either[IllegalValueError[?], Int] =
  for   
    a <- x
    b <- y
  yield a * b

def pow(z: Int): Either[IllegalValueError[?], Int] = mult(z, z)

pow(5)
```
The same is available as a Scastie [here](https://scastie.scala-lang.org/mcallisto/LCL6kiFsTHKcx0LWgnVmYg/28)

**Expected behavior**
Up to Scala version 3.1.0 included
`Right(25): scala.util.Either[io.github.iltotore.iron.constraint.IllegalValueError[_ >: scala.Nothing <: scala.Any], scala.Int]`

**Current behavior**
With Scala version 3.1.1
the `pow` method fails to compile, with the following error:
```
cannot reduce inline match with
 scrutinee:  0 : (0 : Int)
 patterns :  case b @ _:Int if a.>(b)
             case b @ _:Int if a.==(b)
             case b @ _:Int if a.<(b)
             case b @ _:Int
```

**Comment by Iltotore** [comment]
Hello.
Scala 3.1.1 introduced some inline/type-inference bugs fixed in 3.1.2. Can you test Iron with this version ?

Your code works if we specify `Int > 0` in your `pow` method. Since we cannot prove that `Int` is a `Int > 0` at compile-time, Iron tries to use the compile-time value of `z` but Scala 3.1.0 restrained this behaviour to only fully inlined values.

Iron will receive a major release around this summer which will forbid this manipulation in profit of a more explicit fully safe refined type system.

To fix this issue, simply specify `Int > 0` instead of `Int` for `z` in `pow`.

Also note since Iron 1.2.0, you can simplify your code into ([Scastie](https://scastie.scala-lang.org/LQCoCcI9Quqks6dNKzUopA)):
```scala
import io.github.iltotore.iron.{*, given}
import io.github.iltotore.iron.constraint.{*, given}
import io.github.iltotore.iron.numeric.constraint.{*, given}

def mult(x: Int > 0, y: Int > 0): Raw[Int] = refined {
  x * y
}

def pow(z: Int > 0): Raw[Int] = mult(z, z)

pow(5)
```

**Comment by mcallisto** [comment]
Tried now on Scastie with 3.1.2 RC1 and the error seems to stay the same.

Specifying `Int > 0` is of course doable, but this manipulation kept the code simpler, no need to propagate the constrain.

**Comment by Iltotore** [comment]
> Specifying Int > 0 is of course doable, but this manipulation kept the code simpler, no need to propagate the constraint.

I dont think this explicitation is redundant and it ensures the algebraic consistency of the program/method without depending on the call itself (while your example might not work if z is unknown at runtime). In fact, forcing this explicitation makes refined types behaving like "normal" Scala types.

Anyway, I am still open to discussion and suggestions about this topic.

**Comment by mcallisto** [comment]
Thank you for all the replies, I see your point.
I am not able to give a sound opinion right now, I will try to experiment a little more in depth.
