### ISSUE TITLE
Scala.js support

### ISSUE THREAD

**Issue by gvolpe** [Iltotore/iron#63]
Hi,

First of all, thanks a lot for all the work you've put into this library! I really like it so far 🤩 

I decided to feature it in my [upcoming book](https://leanpub.com/feda), you can see the corresponding [Pull Request](https://github.com/gvolpe/trading/pull/204).

The Trading application where it's being used cross-compiles its `domain` module to JS/JVM, so I was wondering if Scala.js support was planned at some point? For now, I got away by having two different implementations of the `Symbol` datatype, one for each platform.

---

A few other things that would be awesome to add would be Cats' typeclass instances support. I added the ones I needed in my PR, but I guess it's so common, this could land in the Cats module (happy to contribute the initial ones!).

```scala
import cats.*
import io.github.iltotore.iron.*

object IronCatsInstances:
  inline given [A, B](using inline ev: Eq[A]): Eq[A :| B] = ev.asInstanceOf[Eq[A :| B]]
  inline given [A, B](using inline ev: Order[A]): Order[A :| B] = ev.asInstanceOf[Order[A :| B]]
  inline given [A, B](using inline ev: Show[A]): Show[A :| B] = ev.asInstanceOf[Show[A :| B]]
```

- [x] Rename modules' package
- [x] Add Cats' typeclass instances
- [x] Add ScalaJS and ScalaNative support

**Comment by Iltotore** [comment]
Hi.

Thank you for featuring Iron in your book!

The ScalaJS and ScalaNative support is planned for 2.0.0. Theoritically, simply enabling cross-compilation via Mill should do the trick.

About the Cats module, I will lack of time this week. Don't hesitate to submit the changes in a pull request. I will do it the next week otherwise.

**Comment by gvolpe** [comment]
That's awesome, thank you! 

Happy to submit a PR today! Meant to ask, can [this](https://github.com/Iltotore/iron/blob/dev/v2.0/cats/src/io/github/iltotore/iron/catsSupport/package.scala#L9) be renamed to `cats` instead? Or what was the reasoning for naming it `catsSupport`? It is a bit unconventional 😄 

For instance, Refined defines them under `eu.timepit.refined.cats`. Same with `circeSupport`, e.g. `org.http4s.circe`, etc

**Comment by Iltotore** [comment]
> Happy to submit a PR today! Meant to ask, can [this](https://github.com/Iltotore/iron/blob/dev/v2.0/cats/src/io/github/iltotore/iron/catsSupport/package.scala?rgh-link-date=2022-11-27T12%3A45%3A01Z#L9) be renamed to cats instead? Or what was the reasoning for naming it catsSupport? It is a bit unconventional 😄

Since it is relatively common to import `io.github.iltotore.iron.*`, a package named `cats` would clash with `_root__.cats` which is the main package of Cats and to stay coherent I applied the same reasoning for other "support" modules. Maybe something like `io.github.iltotore.iron.support.cats` is more appropriated?

**Comment by gvolpe** [comment]
I personally think that's not a problem, as it's how many other packages define it. I think there's even a Scalafix rule somewhere that disallows relative imports and enforces the recommendation of preferring to import the full package name.

```scala
import cats.*
import io.github.iltotore.iron.*
import io.github.iltotore.iron.cats.*
```

Can't seem to find it now, but there's [expandRelative](https://github.com/liancheng/scalafix-organize-imports#24-expandrelative).

Anyway, I understand if this is not your preference. I would definitely take any of `iron.module.cats`, `iron.ext.cats` or `iron.support.cats` over `iron.catsSupport` any day 😃

**Comment by Iltotore** [comment]
Wouldn't `import io.github.iltotore.iron.*` clash with Cats if the sub package is named `cats`, even if imported absolutely? Does the import order have any consequence here?

> Anyway, I understand if this is not your preference. I would definitely take any of iron.module.cats, iron.ext.cats or iron.support.cats over iron.catsSupport any day 😃

I take note of this suggestion. I will ask other users about it.

**Comment by Override-6** [comment]
Be proud mr totore it's the beginning 🎉

**Comment by gvolpe** [comment]
> Wouldn't import io.github.iltotore.iron.* clash with Cats if the sub package is named cats, even if imported absolutely? Does the import order have any consequence here?

Absolutely. Though, most people and organize-imports tooling would have them ordered alphabetically. I'd argue it's very uncommon to do otherwise.

> I take note of this suggestion. I will ask other users about it.

Thank you! ❤️

**Comment by Iltotore** [comment]
Update about the package naming discussion: since it doesn't seem to disturb the asked users, and since similar projects like Refined use this scheme without complaint from their users, removing the "Support" suffix from compatibility packages (i.e `catsSupport` -> `cats`) seems to be the best solution (right now).

**Comment by gvolpe** [comment]
Cool! I can submit a PR including the typeclass instances with the package rename this weekend if that's ok with you.

**Comment by Iltotore** [comment]
I should be available this weekend. And even if I'm not, nothing prevents you to submit the PR and I'll check it as fast as possible.

**Comment by lapin-b** [comment]
Since you can alias imports in Scala, we can have the support package named as `io.github.iltotore.iron.ext.cats` and let the lib user deal with clashes with — maybe — aliasing. Obviously, the package name is just an example.

In Rust, I'd alias the import if referencing it by its absolute path is bothering me. Would the same be fine in Scala ?

PS: While I'm definitely not a Scala dev, I've been requested some feedback and I think pitching in how I would deal with conflicting imports and give my point of view on naming stuff would be valuable.

**Comment by Iltotore** [comment]
> and let the lib user deal with clashes with — maybe — aliasing. Obviously, the package name is just an example.

Yes. Finally, letting the user dealing with this and not adding a `Support` suffix (again, like Refined) seems to be the way.
