### ISSUE TITLE
Scalacheck support

### ISSUE THREAD

**Issue by hejfelix** [Iltotore/iron#66]
**Is your feature request related to a problem? Please describe.**
I would like to use the library with scalacheck

**Describe the solution you'd like**
Introduce a module to derive `Arbitrary` instances for use with Scalacheck. 

I realize this might be difficult for e.g. regexes, but I would be happy with something that works for lengths and bounds, since regex constraints often imply some pretty specific generators that the user should define.

**Comment by Iltotore** [comment]
My knowledge about Scalacheck is pretty limited. Do you mean creating custom `Gen` instances for refined types?

If yes, then it is possible to create in a lib `Gen` instances for each IronType manually (e.g `Gen[Int :| Greater[V]]`) but note you can barely fully "automatize" their creation. For example, you can't create (AFAIK, again my knowledge about Scalacheck isn't big) a `Gen[A :| B]` that works for all inner type `A` with constraint any `B`. The lib would need to contain atleast an instance of `Gen` by constraint.

That's not a big issue however. Since Scalacheck is a big and widely used project, a new module `iron-scalacheck` sounds legit to me.

**Comment by hejfelix** [comment]
I think you're right, and that approach would work great. Not sure how it would work with composed constraints, but maybe we could be inspired by `refined-scalacheck`

**Comment by hejfelix** [comment]
https://github.com/fthomas/refined/blob/master/modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/numeric.scala

Here is how they do it for numeric types

**Comment by Iltotore** [comment]
It should be simple to make a gen for constraint unions but I don't know how to make a generic Gen for constraint intersections right now.
